### ISSUE TITLE
request for releasing openhrp3

### ISSUE THREAD

**Issue by k-okada** [start-jsk/openhrp3#19]
please relase current version, this may fixed rtm-config/openrtm-aist.pc, please keep package version to 3.1.5, which we want sync with original verison

**Comment by 130s** [comment]
I opened [a discussion](https://code.google.com/p/rtm-ros-robotics/issues/detail?id=165#c13) about
more intuitive way of versioning both compliant upstream package and
rtm-ros package. Once it gets settled I'll get to work on this.

**Comment by 130s** [comment]
Done http://code.google.com/p/rtm-ros-robotics/issues/detail?id=165#c20
