### ISSUE TITLE
Build failing on Arch Linux

### ISSUE THREAD

**Issue by bchretien** [start-jsk/openhrp3#26]
When packaging `openhrp3` on Arch Linux, I found 2 errors:
- there are attemps to link with `boost_*-mt`. However, the `-mt` suffix has been removed for years in several Linux distributions now (it was just a symlink AFAIK). I currently use this patch: https://github.com/bchretien/openhrp3/commit/8c28cb872c376e01f5a8782dcf4bc3bb91159185
- I had `undefined reference` errors when linking to `cblas`. I fixed it with this patch: https://github.com/bchretien/openhrp3/commit/1bebaa5e8d67f3c2e3dca9573e35e0bdf49e9941

This may also concern Fedora (cc @cottsay). Now the build completes, and I will try to make some run-time tests before making a PR.

**Comment by k-okada** [comment]
Thanks for the patch, I create PR #29 and It seems working OK for ubuntu environment.
