### ISSUE TITLE
Torque limit calculation in ColladaWriter.h

### ISSUE THREAD

**Issue by orikuma** [start-jsk/openhrp3#49]
ColladaWriter.hにおいてdaeのaccelerationに書き込む値がclimit[0]になっていますが, wrlのclimitは電流リミットです. 従ってトルク上限値としてaccelerationを利用する場合, climit_torqueConst_gearRatioを計算する必要があります.
nominal_torqueの値はclimit_torqueConst_gearRatioになっていますが, 依然としてeuscollada, collada-parserにおいてはcolladaのトルク上限としてはaccelerationが参照されているようなので, こちらも変更しておく必要があるかと思います.
もしくはnominal_torqueを利用するような変更をeuscollada, export-colladaに対して掛けるべきでしょうか?

参考: https://openrtp.jp/redmine/issues/2162

**Comment by k-okada** [comment]
please send patches to https://openrtp.jp/redmine/issues
https://openrtp.jp/redmine/issues/2162, if you do not have access
@YoheiKakiuchi can help

**Comment by k-okada** [comment]
I thinks this has been fixed in openhrp3 upstream repository, please reopen this PR if we need to change something on start-jsk/openhrp3
