### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by dirk-thomas** [start-jsk/openhrp3#58]
http://54.183.26.131:8080/job/Ibin_uT64__openhrp3__ubuntu_trusty_amd64__binary/4/console

```
CMake Error at CMakeLists.txt:558 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command
```

The new build farm job is building the release package with tests disabled - I don't know if that is related. I was unable to configure the package locally because of dependency problems and can therefore not provide more detailed information.

**Comment by k-okada** [comment]
thanks for info, this should be fixed in 
https://github.com/ros/rosdistro/pull/7253

## 

◉ Kei Okada

**Comment by dirk-thomas** [comment]
Same for `hrpsys` now: http://54.183.26.131:8080/job/Ibin_uT64__hrpsys__ubuntu_trusty_amd64__binary/7/console

**Comment by 130s** [comment]
Looks like this is fixed. http://54.183.26.131:8080/job/Ibin_uT64__openhrp3__ubuntu_trusty_amd64__binary/6/console
